baseURL = "https://mcintdre000.github.io/pinnacle-realty/"
languageCode = "en-us"
title = "Pinnacle Realty Group"
theme = "ananke"

[params]
  description = "Your trusted Phoenix-area real estate experts."
  featured_image = "/images/Luxory1.jpg"
  site_logo = "/images/logo.png"
  background_color_class = "bg-near-black"

[[params.ows]]
  name = "Pinnacle Realty Group"

[params.social]
  phone = "(602) 555-0198"
  email = "contact@pinnaclerealty.com"